version: '3.8'

services:
  spring:
    image: ${DOCKER_LOGIN_USERNAME}/${DEV_REPONAME}:latest
    container_name: lost-batch
    ports:
      - "8081:8080"
    networks:
      - lost_network-batch

  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-dev
    ports:
      - "9091:8080"
      - "50000:50000"
    volumes:
      - jenkins_home_dev:/var/jenkins_home
    networks:
      - lost_network_batch

volumes:
  jenkins_home_dev:

networks:
  lost_network_batch: