spring:
  profiles:
    default: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul

  batch:
    job:
      fail-on-job-failure: true
      enabled: true
    jdbc:
      initialize-schema: never

server:
  timezone: Asia/Seoul

logging:
  level:
    org.springframework.data.elasticsearch.client: DEBUG
    org.elasticsearch.client: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG